---
- block:

    - name: create config path
      file:
        state: directory
        path: "{{ prometheus_blackbox_exporter_conf_path }}"
        owner: "{{ prometheus_blackbox_exporter_user }}"
        group: "{{ prometheus_blackbox_exporter_group }}"
        mode: "u=rwX,g=rX,o=rX"

    - name: copy files
      copy:
        content: "{{ prometheus_blackbox_exporter_config }}"
        dest: "{{ prometheus_blackbox_exporter_conf_path }}/{{ prometheus_blackbox_exporter_conf_file }}"
        owner: "{{ prometheus_blackbox_exporter_user }}"
        group: "{{ prometheus_blackbox_exporter_group }}"
        mode: "u=rw,g=r,o=r"
      notify:
        - restart service

  become: true
  become_user: root

  tags:
    - prometheus_blackbox_exporter
